### ISSUE TITLE
Fetch `dove` with new `get-dove` action ❤️

### ISSUE THREAD

**Issue by fzzr-** [pontem-network/intellij-move#17]
Instead of [this](https://github.com/pontem-network/intellij-move/blob/master/.github/workflows/check.yml#L31-L55) just use [these 4 lines](https://github.com/pontem-network/move-stdlib/blob/master/.github/workflows/ci.yaml#L22-L26).

```yaml
      - name: Fetch latest move-tools dove binary
        uses: pontem-network/get-dove@main
        with:
          version: ${{ matrix.dove-version }}
          token: ${{ secrets.GITHUB_TOKEN }}
```
